if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/ImplRK3Prey/ImplRK3Prey_test_mastersolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/ImplRK3Prey/ImplRK3Prey_test_mastersolution[1]_tests.cmake")
else()
  add_test(ImplRK3Prey_test_mastersolution_NOT_BUILT ImplRK3Prey_test_mastersolution_NOT_BUILT)
endif()
