if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/LengthOfBoundary/LengthOfBoundary_test_mysolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/LengthOfBoundary/LengthOfBoundary_test_mysolution[1]_tests.cmake")
else()
  add_test(LengthOfBoundary_test_mysolution_NOT_BUILT LengthOfBoundary_test_mysolution_NOT_BUILT)
endif()
