if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/IPDGFEM/IPDGFEM_test_mastersolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/IPDGFEM/IPDGFEM_test_mastersolution[1]_tests.cmake")
else()
  add_test(IPDGFEM_test_mastersolution_NOT_BUILT IPDGFEM_test_mastersolution_NOT_BUILT)
endif()
