if(EXISTS "/home/fuchsja/NPDECODES/built/developers/PotentialFlow/PotentialFlow_test_mastersolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/PotentialFlow/PotentialFlow_test_mastersolution_dev[1]_tests.cmake")
else()
  add_test(PotentialFlow_test_mastersolution_dev_NOT_BUILT PotentialFlow_test_mastersolution_dev_NOT_BUILT)
endif()
