if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/LinFeReactDiff/LinFeReactDiff_test_mysolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/LinFeReactDiff/LinFeReactDiff_test_mysolution[1]_tests.cmake")
else()
  add_test(LinFeReactDiff_test_mysolution_NOT_BUILT LinFeReactDiff_test_mysolution_NOT_BUILT)
endif()
