if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/TaylorODE/TaylorODE_test_mastersolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/TaylorODE/TaylorODE_test_mastersolution[1]_tests.cmake")
else()
  add_test(TaylorODE_test_mastersolution_NOT_BUILT TaylorODE_test_mastersolution_NOT_BUILT)
endif()
