if(EXISTS "/home/fuchsja/NPDECODES/built/developers/InitCondLV/InitCondLV_test_mysolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/InitCondLV/InitCondLV_test_mysolution_dev[1]_tests.cmake")
else()
  add_test(InitCondLV_test_mysolution_dev_NOT_BUILT InitCondLV_test_mysolution_dev_NOT_BUILT)
endif()
