if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/ExtendedMUSCL/ExtendedMUSCL_test_mysolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/ExtendedMUSCL/ExtendedMUSCL_test_mysolution[1]_tests.cmake")
else()
  add_test(ExtendedMUSCL_test_mysolution_NOT_BUILT ExtendedMUSCL_test_mysolution_NOT_BUILT)
endif()
