if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/ProjectionOntoGradients/ProjectionOntoGradients_test_mysolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/ProjectionOntoGradients/ProjectionOntoGradients_test_mysolution[1]_tests.cmake")
else()
  add_test(ProjectionOntoGradients_test_mysolution_NOT_BUILT ProjectionOntoGradients_test_mysolution_NOT_BUILT)
endif()
