if(EXISTS "/home/fuchsja/NPDECODES/built/developers/WaveABC2D/WaveABC2D_test_mastersolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/WaveABC2D/WaveABC2D_test_mastersolution_dev[1]_tests.cmake")
else()
  add_test(WaveABC2D_test_mastersolution_dev_NOT_BUILT WaveABC2D_test_mastersolution_dev_NOT_BUILT)
endif()
