if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/UnstableBVP/UnstableBVP_test_mastersolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/UnstableBVP/UnstableBVP_test_mastersolution[1]_tests.cmake")
else()
  add_test(UnstableBVP_test_mastersolution_NOT_BUILT UnstableBVP_test_mastersolution_NOT_BUILT)
endif()
