if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/RK3Prey/RK3Prey_test_mastersolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/RK3Prey/RK3Prey_test_mastersolution[1]_tests.cmake")
else()
  add_test(RK3Prey_test_mastersolution_NOT_BUILT RK3Prey_test_mastersolution_NOT_BUILT)
endif()
