if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/BoundaryWave/BoundaryWave_test_mysolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/BoundaryWave/BoundaryWave_test_mysolution[1]_tests.cmake")
else()
  add_test(BoundaryWave_test_mysolution_NOT_BUILT BoundaryWave_test_mysolution_NOT_BUILT)
endif()
