if(EXISTS "/home/fuchsja/NPDECODES/built/developers/ExtendedMUSCL/ExtendedMUSCL_test_mysolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/ExtendedMUSCL/ExtendedMUSCL_test_mysolution_dev[1]_tests.cmake")
else()
  add_test(ExtendedMUSCL_test_mysolution_dev_NOT_BUILT ExtendedMUSCL_test_mysolution_dev_NOT_BUILT)
endif()
