if(EXISTS "/home/fuchsja/NPDECODES/built/developers/NumPDESetup/NumPDESetup_test_mysolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/NumPDESetup/NumPDESetup_test_mysolution_dev[1]_tests.cmake")
else()
  add_test(NumPDESetup_test_mysolution_dev_NOT_BUILT NumPDESetup_test_mysolution_dev_NOT_BUILT)
endif()
