if(EXISTS "/home/fuchsja/NPDECODES/built/developers/MaximumPrinciple/MaximumPrinciple_test_mastersolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/MaximumPrinciple/MaximumPrinciple_test_mastersolution_dev[1]_tests.cmake")
else()
  add_test(MaximumPrinciple_test_mastersolution_dev_NOT_BUILT MaximumPrinciple_test_mastersolution_dev_NOT_BUILT)
endif()
