# Install script for directory: /home/fuchsja/NPDECODES/homeworks

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "1")
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

# Set default install directory permissions.
if(NOT DEFINED CMAKE_OBJDUMP)
  set(CMAKE_OBJDUMP "/usr/bin/objdump")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/fuchsja/NPDECODES/built/homeworks/1DWaveAbsorbingBC/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/AdvectionFV2D/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/AvgValBoundary/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/BoundaryWave/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/BurgersEquation/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/CLEmpiricFlux/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/ConsLawWithSource/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/ContourPlot/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/ConvBLFMatrixProvider/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/CoupledSecondOrderBVP/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/CrossProd/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/DebuggingFEM/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/DebuggingWithGDB/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/DiscontinuousGalerkin1D/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/ElectrostaticForce/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/ElementMatrixComputation/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/EngquistOsherNumericalFlux/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/ErrorEstimatesForTraces/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/ExpFittedUpwind/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/ExponentialIntegrator/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/ExtendedMUSCL/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/FiniteVolumeRobin/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/FiniteVolumeSineConsLaw/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/FluxLimitedFV/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/GaussLobattoParabolic/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/GradientFlow/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/HierarchicalErrorEstimator/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/ImplRK3Prey/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/IncidenceMatrices/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/InitCondLV/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/IPDGFEM/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/LengthOfBoundary/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/LFPPDofHandling/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/LinearFE1D/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/LinFeReactDiff/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/MatODE/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/MaximumPrinciple/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/MIRK/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/MixedFEMWave/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/NitscheMethod/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/NLMatODE/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/NonConformingCrouzeixRaviartFiniteElements/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/NonLinSchroedingerEquation/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/NumPDESetup/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/ODESolve/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/OrdNotAll/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/OutputImpedanceBVP/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/ParametricElementMatrices/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/ParametricFiniteElements/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/PointEvaluationRhs/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/ProjectionOntoGradients/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/QuasiInterpolation/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/RadauThreeTimestepping/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/RegularizedNeumannProblem/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/ResidualErrorEstimator/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/RK3Prey/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/SDIRK/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/SDIRKMethodOfLines/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/SemImpRK/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/SimpleLinearFiniteElements/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/SobolevEvolutionProblem/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/StableEvaluationAtAPoint/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/StabRK3/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/StationaryCurrents/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/SymplecticTimestepping/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/SymplecticTimesteppingWaves/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/SystemODE/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/TaylorODE/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/TestQuadratureRules/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/TransformationOfGalerkinMatrices/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/TransformedConsLaw/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/TranspSemiLagr/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/UnstableBVP/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/UpwindFiniteVolume/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/UpwindQuadrature/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/WaveABC2D/cmake_install.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/ZienkiewiczZhuEstimator/cmake_install.cmake")

endif()

