if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/DebuggingFEM/DebuggingFEM_test_mysolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/DebuggingFEM/DebuggingFEM_test_mysolution[1]_tests.cmake")
else()
  add_test(DebuggingFEM_test_mysolution_NOT_BUILT DebuggingFEM_test_mysolution_NOT_BUILT)
endif()
