if(EXISTS "/home/fuchsja/NPDECODES/built/developers/SDIRKMethodOfLines/SDIRKMethodOfLines_test_mysolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/SDIRKMethodOfLines/SDIRKMethodOfLines_test_mysolution_dev[1]_tests.cmake")
else()
  add_test(SDIRKMethodOfLines_test_mysolution_dev_NOT_BUILT SDIRKMethodOfLines_test_mysolution_dev_NOT_BUILT)
endif()
