if(EXISTS "/home/fuchsja/NPDECODES/built/developers/ParametricFiniteElements/ParametricFiniteElements_test_mastersolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/ParametricFiniteElements/ParametricFiniteElements_test_mastersolution_dev[1]_tests.cmake")
else()
  add_test(ParametricFiniteElements_test_mastersolution_dev_NOT_BUILT ParametricFiniteElements_test_mastersolution_dev_NOT_BUILT)
endif()
