if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/ErrorEstimatesForTraces/ErrorEstimatesForTraces_test_mysolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/ErrorEstimatesForTraces/ErrorEstimatesForTraces_test_mysolution[1]_tests.cmake")
else()
  add_test(ErrorEstimatesForTraces_test_mysolution_NOT_BUILT ErrorEstimatesForTraces_test_mysolution_NOT_BUILT)
endif()
