if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/InitCondLV/InitCondLV_test_mysolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/InitCondLV/InitCondLV_test_mysolution[1]_tests.cmake")
else()
  add_test(InitCondLV_test_mysolution_NOT_BUILT InitCondLV_test_mysolution_NOT_BUILT)
endif()
