if(EXISTS "/home/fuchsja/NPDECODES/built/developers/IncidenceMatrices/IncidenceMatrices_test_mastersolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/IncidenceMatrices/IncidenceMatrices_test_mastersolution_dev[1]_tests.cmake")
else()
  add_test(IncidenceMatrices_test_mastersolution_dev_NOT_BUILT IncidenceMatrices_test_mastersolution_dev_NOT_BUILT)
endif()
