if(EXISTS "/home/fuchsja/NPDECODES/built/developers/ConsLawWithSource/ConsLawWithSource_test_mastersolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/ConsLawWithSource/ConsLawWithSource_test_mastersolution_dev[1]_tests.cmake")
else()
  add_test(ConsLawWithSource_test_mastersolution_dev_NOT_BUILT ConsLawWithSource_test_mastersolution_dev_NOT_BUILT)
endif()
