if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/TestQuadratureRules/TestQuadratureRules_test_mastersolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/TestQuadratureRules/TestQuadratureRules_test_mastersolution[1]_tests.cmake")
else()
  add_test(TestQuadratureRules_test_mastersolution_NOT_BUILT TestQuadratureRules_test_mastersolution_NOT_BUILT)
endif()
