if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/CoupledSecondOrderBVP/CoupledSecondOrderBVP_test_mysolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/CoupledSecondOrderBVP/CoupledSecondOrderBVP_test_mysolution[1]_tests.cmake")
else()
  add_test(CoupledSecondOrderBVP_test_mysolution_NOT_BUILT CoupledSecondOrderBVP_test_mysolution_NOT_BUILT)
endif()
