if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/SimpleLinearFiniteElements/SimpleLinearFiniteElements_test_mysolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/SimpleLinearFiniteElements/SimpleLinearFiniteElements_test_mysolution[1]_tests.cmake")
else()
  add_test(SimpleLinearFiniteElements_test_mysolution_NOT_BUILT SimpleLinearFiniteElements_test_mysolution_NOT_BUILT)
endif()
