if(EXISTS "/home/fuchsja/NPDECODES/built/developers/ProjectionOntoGradients/ProjectionOntoGradients_test_mastersolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/ProjectionOntoGradients/ProjectionOntoGradients_test_mastersolution_dev[1]_tests.cmake")
else()
  add_test(ProjectionOntoGradients_test_mastersolution_dev_NOT_BUILT ProjectionOntoGradients_test_mastersolution_dev_NOT_BUILT)
endif()
