if(EXISTS "/home/fuchsja/NPDECODES/built/developers/SystemODE/SystemODE_test_mysolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/SystemODE/SystemODE_test_mysolution_dev[1]_tests.cmake")
else()
  add_test(SystemODE_test_mysolution_dev_NOT_BUILT SystemODE_test_mysolution_dev_NOT_BUILT)
endif()
