if(EXISTS "/home/fuchsja/NPDECODES/built/developers/ParametricElementMatrices/ParametricElementMatrices_test_mastersolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/ParametricElementMatrices/ParametricElementMatrices_test_mastersolution_dev[1]_tests.cmake")
else()
  add_test(ParametricElementMatrices_test_mastersolution_dev_NOT_BUILT ParametricElementMatrices_test_mastersolution_dev_NOT_BUILT)
endif()
