if(EXISTS "/home/fuchsja/NPDECODES/built/developers/ExpFittedUpwind/ExpFittedUpwind_test_mastersolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/ExpFittedUpwind/ExpFittedUpwind_test_mastersolution_dev[1]_tests.cmake")
else()
  add_test(ExpFittedUpwind_test_mastersolution_dev_NOT_BUILT ExpFittedUpwind_test_mastersolution_dev_NOT_BUILT)
endif()
