if(EXISTS "/home/fuchsja/NPDECODES/built/developers/NLMatODE/NLMatODE_test_mastersolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/NLMatODE/NLMatODE_test_mastersolution_dev[1]_tests.cmake")
else()
  add_test(NLMatODE_test_mastersolution_dev_NOT_BUILT NLMatODE_test_mastersolution_dev_NOT_BUILT)
endif()
