if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/SDIRKMethodOfLines/SDIRKMethodOfLines_test_mysolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/SDIRKMethodOfLines/SDIRKMethodOfLines_test_mysolution[1]_tests.cmake")
else()
  add_test(SDIRKMethodOfLines_test_mysolution_NOT_BUILT SDIRKMethodOfLines_test_mysolution_NOT_BUILT)
endif()
