if(EXISTS "/home/fuchsja/NPDECODES/built/developers/TranspSemiLagr/TranspSemiLagr_test_mastersolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/TranspSemiLagr/TranspSemiLagr_test_mastersolution_dev[1]_tests.cmake")
else()
  add_test(TranspSemiLagr_test_mastersolution_dev_NOT_BUILT TranspSemiLagr_test_mastersolution_dev_NOT_BUILT)
endif()
