if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/LFPPDofHandling/LFPPDofHandling_test_mysolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/LFPPDofHandling/LFPPDofHandling_test_mysolution[1]_tests.cmake")
else()
  add_test(LFPPDofHandling_test_mysolution_NOT_BUILT LFPPDofHandling_test_mysolution_NOT_BUILT)
endif()
