if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/ExpFittedUpwind/ExpFittedUpwind_test_mastersolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/ExpFittedUpwind/ExpFittedUpwind_test_mastersolution[1]_tests.cmake")
else()
  add_test(ExpFittedUpwind_test_mastersolution_NOT_BUILT ExpFittedUpwind_test_mastersolution_NOT_BUILT)
endif()
