if(EXISTS "/home/fuchsja/NPDECODES/built/developers/TransformedConsLaw/TransformedConsLaw_test_mysolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/TransformedConsLaw/TransformedConsLaw_test_mysolution_dev[1]_tests.cmake")
else()
  add_test(TransformedConsLaw_test_mysolution_dev_NOT_BUILT TransformedConsLaw_test_mysolution_dev_NOT_BUILT)
endif()
