if(EXISTS "/home/fuchsja/NPDECODES/built/developers/RK3Prey/RK3Prey_test_mysolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/RK3Prey/RK3Prey_test_mysolution_dev[1]_tests.cmake")
else()
  add_test(RK3Prey_test_mysolution_dev_NOT_BUILT RK3Prey_test_mysolution_dev_NOT_BUILT)
endif()
