if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/MixedFEMWave/MixedFEMWave_test_mysolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/MixedFEMWave/MixedFEMWave_test_mysolution[1]_tests.cmake")
else()
  add_test(MixedFEMWave_test_mysolution_NOT_BUILT MixedFEMWave_test_mysolution_NOT_BUILT)
endif()
