if(EXISTS "/home/fuchsja/NPDECODES/built/developers/DiscontinuousGalerkin1D/DiscontinuousGalerkin1D_test_mastersolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/DiscontinuousGalerkin1D/DiscontinuousGalerkin1D_test_mastersolution_dev[1]_tests.cmake")
else()
  add_test(DiscontinuousGalerkin1D_test_mastersolution_dev_NOT_BUILT DiscontinuousGalerkin1D_test_mastersolution_dev_NOT_BUILT)
endif()
