if(EXISTS "/home/fuchsja/NPDECODES/built/developers/ContourPlot/ContourPlot_test_mysolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/ContourPlot/ContourPlot_test_mysolution_dev[1]_tests.cmake")
else()
  add_test(ContourPlot_test_mysolution_dev_NOT_BUILT ContourPlot_test_mysolution_dev_NOT_BUILT)
endif()
