if(EXISTS "/home/fuchsja/NPDECODES/built/developers/ExponentialIntegrator/ExponentialIntegrator_test_mastersolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/ExponentialIntegrator/ExponentialIntegrator_test_mastersolution_dev[1]_tests.cmake")
else()
  add_test(ExponentialIntegrator_test_mastersolution_dev_NOT_BUILT ExponentialIntegrator_test_mastersolution_dev_NOT_BUILT)
endif()
