if(EXISTS "/home/fuchsja/NPDECODES/built/developers/FiniteVolumeRobin/FiniteVolumeRobin_test_mysolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/FiniteVolumeRobin/FiniteVolumeRobin_test_mysolution_dev[1]_tests.cmake")
else()
  add_test(FiniteVolumeRobin_test_mysolution_dev_NOT_BUILT FiniteVolumeRobin_test_mysolution_dev_NOT_BUILT)
endif()
