if(EXISTS "/home/fuchsja/NPDECODES/built/developers/SemiLagrangian/SemiLagrangian_test_mysolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/SemiLagrangian/SemiLagrangian_test_mysolution_dev[1]_tests.cmake")
else()
  add_test(SemiLagrangian_test_mysolution_dev_NOT_BUILT SemiLagrangian_test_mysolution_dev_NOT_BUILT)
endif()
