if(EXISTS "/home/fuchsja/NPDECODES/built/developers/AdvectionFV2D/AdvectionFV2D_test_mastersolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/AdvectionFV2D/AdvectionFV2D_test_mastersolution_dev[1]_tests.cmake")
else()
  add_test(AdvectionFV2D_test_mastersolution_dev_NOT_BUILT AdvectionFV2D_test_mastersolution_dev_NOT_BUILT)
endif()
