if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/ConsLawWithSource/ConsLawWithSource_test_mastersolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/ConsLawWithSource/ConsLawWithSource_test_mastersolution[1]_tests.cmake")
else()
  add_test(ConsLawWithSource_test_mastersolution_NOT_BUILT ConsLawWithSource_test_mastersolution_NOT_BUILT)
endif()
