if(EXISTS "/home/fuchsja/NPDECODES/built/developers/SymplecticTimestepping/SymplecticTimestepping_test_mysolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/SymplecticTimestepping/SymplecticTimestepping_test_mysolution_dev[1]_tests.cmake")
else()
  add_test(SymplecticTimestepping_test_mysolution_dev_NOT_BUILT SymplecticTimestepping_test_mysolution_dev_NOT_BUILT)
endif()
