if(EXISTS "/home/fuchsja/NPDECODES/built/developers/SDIRK/SDIRK_test_mysolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/SDIRK/SDIRK_test_mysolution_dev[1]_tests.cmake")
else()
  add_test(SDIRK_test_mysolution_dev_NOT_BUILT SDIRK_test_mysolution_dev_NOT_BUILT)
endif()
