if(EXISTS "/home/fuchsja/NPDECODES/built/developers/UpwindQuadrature/UpwindQuadrature_test_mysolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/UpwindQuadrature/UpwindQuadrature_test_mysolution_dev[1]_tests.cmake")
else()
  add_test(UpwindQuadrature_test_mysolution_dev_NOT_BUILT UpwindQuadrature_test_mysolution_dev_NOT_BUILT)
endif()
