if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/GradientFlow/GradientFlow_test_mastersolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/GradientFlow/GradientFlow_test_mastersolution[1]_tests.cmake")
else()
  add_test(GradientFlow_test_mastersolution_NOT_BUILT GradientFlow_test_mastersolution_NOT_BUILT)
endif()
