if(EXISTS "/home/fuchsja/NPDECODES/built/developers/ElementMatrixComputation/ElementMatrixComputation_test_mastersolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/ElementMatrixComputation/ElementMatrixComputation_test_mastersolution_dev[1]_tests.cmake")
else()
  add_test(ElementMatrixComputation_test_mastersolution_dev_NOT_BUILT ElementMatrixComputation_test_mastersolution_dev_NOT_BUILT)
endif()
