if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/ParametricElementMatrices/ParametricElementMatrices_test_mastersolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/ParametricElementMatrices/ParametricElementMatrices_test_mastersolution[1]_tests.cmake")
else()
  add_test(ParametricElementMatrices_test_mastersolution_NOT_BUILT ParametricElementMatrices_test_mastersolution_NOT_BUILT)
endif()
