if(EXISTS "/home/fuchsja/NPDECODES/built/developers/FiniteVolumeSineConsLaw/FiniteVolumeSineConsLaw_test_mastersolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/FiniteVolumeSineConsLaw/FiniteVolumeSineConsLaw_test_mastersolution_dev[1]_tests.cmake")
else()
  add_test(FiniteVolumeSineConsLaw_test_mastersolution_dev_NOT_BUILT FiniteVolumeSineConsLaw_test_mastersolution_dev_NOT_BUILT)
endif()
