if(EXISTS "/home/fuchsja/NPDECODES/built/developers/ODESolve/ODESolve_test_mysolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/ODESolve/ODESolve_test_mysolution_dev[1]_tests.cmake")
else()
  add_test(ODESolve_test_mysolution_dev_NOT_BUILT ODESolve_test_mysolution_dev_NOT_BUILT)
endif()
