if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/LinearFE1D/LinearFE1D_test_mastersolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/LinearFE1D/LinearFE1D_test_mastersolution[1]_tests.cmake")
else()
  add_test(LinearFE1D_test_mastersolution_NOT_BUILT LinearFE1D_test_mastersolution_NOT_BUILT)
endif()
