if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/DiscontinuousGalerkin1D/DiscontinuousGalerkin1D_test_mysolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/DiscontinuousGalerkin1D/DiscontinuousGalerkin1D_test_mysolution[1]_tests.cmake")
else()
  add_test(DiscontinuousGalerkin1D_test_mysolution_NOT_BUILT DiscontinuousGalerkin1D_test_mysolution_NOT_BUILT)
endif()
