if(EXISTS "/home/fuchsja/NPDECODES/built/developers/TestQuadratureRules/TestQuadratureRules_test_mastersolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/TestQuadratureRules/TestQuadratureRules_test_mastersolution_dev[1]_tests.cmake")
else()
  add_test(TestQuadratureRules_test_mastersolution_dev_NOT_BUILT TestQuadratureRules_test_mastersolution_dev_NOT_BUILT)
endif()
