if(EXISTS "/home/fuchsja/NPDECODES/built/developers/CLEmpiricFlux/CLEmpiricFlux_test_mysolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/CLEmpiricFlux/CLEmpiricFlux_test_mysolution_dev[1]_tests.cmake")
else()
  add_test(CLEmpiricFlux_test_mysolution_dev_NOT_BUILT CLEmpiricFlux_test_mysolution_dev_NOT_BUILT)
endif()
