if(EXISTS "/home/fuchsja/NPDECODES/built/developers/LengthOfBoundary/LengthOfBoundary_test_mysolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/LengthOfBoundary/LengthOfBoundary_test_mysolution_dev[1]_tests.cmake")
else()
  add_test(LengthOfBoundary_test_mysolution_dev_NOT_BUILT LengthOfBoundary_test_mysolution_dev_NOT_BUILT)
endif()
