if(EXISTS "/home/fuchsja/NPDECODES/built/developers/QuasiInterpolation/QuasiInterpolation_test_mastersolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/QuasiInterpolation/QuasiInterpolation_test_mastersolution_dev[1]_tests.cmake")
else()
  add_test(QuasiInterpolation_test_mastersolution_dev_NOT_BUILT QuasiInterpolation_test_mastersolution_dev_NOT_BUILT)
endif()
