if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/UpwindFiniteVolume/UpwindFiniteVolume_test_mastersolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/UpwindFiniteVolume/UpwindFiniteVolume_test_mastersolution[1]_tests.cmake")
else()
  add_test(UpwindFiniteVolume_test_mastersolution_NOT_BUILT UpwindFiniteVolume_test_mastersolution_NOT_BUILT)
endif()
