if(EXISTS "/home/fuchsja/NPDECODES/built/developers/GradientFlow/GradientFlow_test_mysolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/GradientFlow/GradientFlow_test_mysolution_dev[1]_tests.cmake")
else()
  add_test(GradientFlow_test_mysolution_dev_NOT_BUILT GradientFlow_test_mysolution_dev_NOT_BUILT)
endif()
