if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/SemImpRK/SemImpRK_test_mastersolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/SemImpRK/SemImpRK_test_mastersolution[1]_tests.cmake")
else()
  add_test(SemImpRK_test_mastersolution_NOT_BUILT SemImpRK_test_mastersolution_NOT_BUILT)
endif()
