if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/ODESolve/ODESolve_test_mysolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/ODESolve/ODESolve_test_mysolution[1]_tests.cmake")
else()
  add_test(ODESolve_test_mysolution_NOT_BUILT ODESolve_test_mysolution_NOT_BUILT)
endif()
