if(EXISTS "/home/fuchsja/NPDECODES/built/developers/NonLinSchroedingerEquation/NonLinSchroedingerEquation_test_mysolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/NonLinSchroedingerEquation/NonLinSchroedingerEquation_test_mysolution_dev[1]_tests.cmake")
else()
  add_test(NonLinSchroedingerEquation_test_mysolution_dev_NOT_BUILT NonLinSchroedingerEquation_test_mysolution_dev_NOT_BUILT)
endif()
