if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/ZienkiewiczZhuEstimator/ZienkiewiczZhuEstimator_test_mastersolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/ZienkiewiczZhuEstimator/ZienkiewiczZhuEstimator_test_mastersolution[1]_tests.cmake")
else()
  add_test(ZienkiewiczZhuEstimator_test_mastersolution_NOT_BUILT ZienkiewiczZhuEstimator_test_mastersolution_NOT_BUILT)
endif()
