if(EXISTS "/home/fuchsja/NPDECODES/built/developers/EngquistOsherNumericalFlux/EngquistOsherNumericalFlux_test_mysolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/EngquistOsherNumericalFlux/EngquistOsherNumericalFlux_test_mysolution_dev[1]_tests.cmake")
else()
  add_test(EngquistOsherNumericalFlux_test_mysolution_dev_NOT_BUILT EngquistOsherNumericalFlux_test_mysolution_dev_NOT_BUILT)
endif()
