if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/IncidenceMatrices/IncidenceMatrices_test_mastersolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/IncidenceMatrices/IncidenceMatrices_test_mastersolution[1]_tests.cmake")
else()
  add_test(IncidenceMatrices_test_mastersolution_NOT_BUILT IncidenceMatrices_test_mastersolution_NOT_BUILT)
endif()
