if(EXISTS "/home/fuchsja/NPDECODES/built/developers/ZienkiewiczZhuEstimator/ZienkiewiczZhuEstimator_test_mastersolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/ZienkiewiczZhuEstimator/ZienkiewiczZhuEstimator_test_mastersolution_dev[1]_tests.cmake")
else()
  add_test(ZienkiewiczZhuEstimator_test_mastersolution_dev_NOT_BUILT ZienkiewiczZhuEstimator_test_mastersolution_dev_NOT_BUILT)
endif()
