if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/StationaryCurrents/StationaryCurrents_test_mysolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/StationaryCurrents/StationaryCurrents_test_mysolution[1]_tests.cmake")
else()
  add_test(StationaryCurrents_test_mysolution_NOT_BUILT StationaryCurrents_test_mysolution_NOT_BUILT)
endif()
