if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/ElectrostaticForce/ElectrostaticForce_test_mysolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/ElectrostaticForce/ElectrostaticForce_test_mysolution[1]_tests.cmake")
else()
  add_test(ElectrostaticForce_test_mysolution_NOT_BUILT ElectrostaticForce_test_mysolution_NOT_BUILT)
endif()
