if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/OutputImpedanceBVP/OutputImpedanceBVP_test_mastersolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/OutputImpedanceBVP/OutputImpedanceBVP_test_mastersolution[1]_tests.cmake")
else()
  add_test(OutputImpedanceBVP_test_mastersolution_NOT_BUILT OutputImpedanceBVP_test_mastersolution_NOT_BUILT)
endif()
