if(EXISTS "/home/fuchsja/NPDECODES/built/developers/ImplRK3Prey/ImplRK3Prey_test_mysolution_dev[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/developers/ImplRK3Prey/ImplRK3Prey_test_mysolution_dev[1]_tests.cmake")
else()
  add_test(ImplRK3Prey_test_mysolution_dev_NOT_BUILT ImplRK3Prey_test_mysolution_dev_NOT_BUILT)
endif()
