if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/CrossProd/CrossProd_test_mastersolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/CrossProd/CrossProd_test_mastersolution[1]_tests.cmake")
else()
  add_test(CrossProd_test_mastersolution_NOT_BUILT CrossProd_test_mastersolution_NOT_BUILT)
endif()
