if(EXISTS "/home/fuchsja/NPDECODES/built/homeworks/RadauThreeTimestepping/RadauThreeTimestepping_test_mysolution[1]_tests.cmake")
  include("/home/fuchsja/NPDECODES/built/homeworks/RadauThreeTimestepping/RadauThreeTimestepping_test_mysolution[1]_tests.cmake")
else()
  add_test(RadauThreeTimestepping_test_mysolution_NOT_BUILT RadauThreeTimestepping_test_mysolution_NOT_BUILT)
endif()
